language: clojure
dist:
  - trusty
env:
  global:
  - secure: k/Yuqkd3AIFvdM7FWeowE+GyZoSH+5wxcH3rM2dno6ZJkBKvWCkcnG44rp2z7xBsdAE25CROKRrelFRjSA8Bqiv54Sz5Jxz5jyrR+JNpJ8pkoQFkpUQoXVOdeokRJgi5k4h3xB3NtTZnOwEIEhlQXAJMkxKaCMGl2bBq7//RRG5vq5QMGPrPBd/eCzHzCLrG+84rAXgp/BP3fW2ppU6M5XBekPWksxvbpNiUcrjAYyyWIZHypGwlgPjee60XyfYsI+5849W5VK9+lzhYY4J0ILlEbpQBrq2AVf88uIgqd8rEmhNWWakR9OoLuuzZaFB1aBmCmj0w5/Yw0yNEwbvsVDPGMwkXZCnsvmlpSIRb/2vltvoGlRDxQqhWhG9QPiyLNryoVvuSQOo1ox22/jdspSxWit3EOQ6Tyai8/aepOERSWBZR0KaQupLVagoRrUXeGf+QfpCUXNOLbmg0w94yGo3uLkhmVHcvLdwulzxp+aFuh0JguRvcy2birRQn8K/4J43H5Zglk1AlPiBTSY7umdtEcCc0P2z96uNcUJw6YK1EJOctPk6vS8CnTJzIV0gg6vVbN4WSykMV3xio+pdhBXj1OAl9s1nj3ej7t4L5Yd2EDApDeWGflrLkMx2BGClPPbkCy6/pgIy9syyGjfMfiZy0ZeVP1NzPT0FoOfnMx8M=
  - secure: ejsNN8YnukumU/MhltV8x6Hq/zPesuJOkyfzJ5A81u1+OgzC9JvVffUTuMrRq4ORKG2yMBfoLGYyeqSRmVdjK1r6+0MoxxELNLpHfN4t7TYZoRuoGzMDbMvxA/ik03Rdf0VOp5P4q68SQuTOiFpniS8KchJRELaqWtl5gTsbs/q7RJgpYy3TR6kIW9eaUhbs02woF3/P/d1Pyd4aD4WoOoe9Um1MgyRMBR6huPf2SfZsy3vaJ5nMiDyada1ORlWb7CscPoiY6RHAzUmoIRysW7nkfCJAeCUXGHk5JgLTJBXt+OP50bLFMPdehzQULOfvawC3o/YBOlrFg9mmeO3uTgYiuhABL7gPdp12wTeCbob0dhv7p27/sobAnOBqNkH/X88L+2e+7IBG4Glpi2VQ+EltlBsI2Zq7rY8D4JAFfTEwy74xjD7mw38OuYkJc+r9QrYgH/h4uJu6VbVIHHorf+3a8cNCycpONrVhqvxlpFXIl1Chz91u6sMtPmbOFeiYm4LxeUj47Poge7vn+h3JRQMb4SLgt3pVueqwM62iBnAZAI42MMGAZhqYC6Ya8wwiIlEcGiTr/Cz5vbAD4ckyQbSCCAiL9PWptbCfiN2kV5/pk9/1wLtYg4KK9j6Uwax7LD0PeRnk8D5n6J/UmFADWuvWYCQNPVLO2dMdPNxnwJQ=
jdk: oraclejdk8
before_install:
- wget https://releases.hashicorp.com/vault/0.6.1/vault_0.6.1_linux_amd64.zip -O vault.zip
- unzip vault.zip
- export PATH=$PATH:$PWD
- vault auth -method=github token=$GITHUB_TOKEN
- ". scripts/core-access"
